class Character < ActiveRecord::Base
	belongs_to :owner, class_name: "User", foreign_key: "owner_id"
	belongs_to :campaign

	validates :name, presence: true, 
  					 length: { maximum: 20 }
  	validates :owner, presence: true
  	validates :campaign, presence: true

  	validates :hp, 			 	 :hp_bonus,
  			  :stamina, 	 	 :stamina_bonus,
  			  :eita, 		  	 :eita_bonus,
  			  :initiative, 	 	 :initiative_bonus,
  			  :adrenaline, 	  	 :adrenaline_bonus,
  			  :focus, 		  	 :focus_bonus,
  			  :strength, 	  	 :strength_bonus,
  			  :constitution,  	 :constitution_bonus,
  			  :dexterity, 	   	 :dexterity_bonus,
  			  :intelligence,  	 :intelligence_bonus,
  			  :wisdom, 		  	 :wisdom_bonus,
  			  :charisma, 	   	 :charisma_bonus,
  			  :block, 		  	 :block_bonus,
  			  :reflex, 		  	 :reflex_bonus,
  			  :resilience, 	  	 :resilience_bonus,
  			  :willpower, 	  	 :willpower_bonus,
  			  :acrobatics, 	  	 :acrobatics_bonus,
  			  :athletics, 	 	 :athletics_bonus,
  			  :endurance,  	 	 :endurance_bonus,
  			  :bluff, 		 	 :bluff_bonus,
  			  :diplomacy, 	 	 :diplomacy_bonus,
  			  :intimidate,	     :intimidate_bonus,
  			  :history,			 :history_bonus,
  			  :insight,		 	 :insight_bonus,
  			  :perception,		 :perception_bonus,
  			  :stealth,			 :stealth_bonus,
  			  :thievery,		 :thievery_bonus,
  			  :beast_mastery,	 :beast_mastery_bonus,
  			  :botany,			 :botany_bonus,
  			  :gathering,		 :gathering_bonus,
  			  :spelunking,		 :spelunking_bonus,
  			  :tracking,		 :tracking_bonus,
  			  :axes,			 :axes_bonus,
  			  :double_axes,		 :double_axes_bonus,
  			  :double_hammers,	 :double_hammers_bonus,
  			  :heavy_blades,	 :heavy_blades_bonus,
  			  :heavy_gauntlets,	 :heavy_gauntlets_bonus,
  			  :mallets,			 :mallets_bonus,
  			  :picks,			 :picks_bonus,
  			  :double_lights,	 :double_lights_bonus,
  			  :hatchets,		 :hatchets_bonus,
  			  :flails,			 :flails_bonus,
  			  :heavy_thrown,	 :heavy_thrown_bonus,
  			  :maces,			 :maces_bonus,
  			  :spears,			 :spears_bonus,
  			  :bombs,			 :bombs_bonus,
  			  :bows,			 :bows_bonus,
  			  :light_blades,	 :light_blades_bonus,
  			  :light_gauntlets,	 :light_gauntlets_bonus,
  			  :light_thrown,	 :light_thrown_bonus,
  			  :slings,			 :slings_bonus,
  			  :blow_darts,		 :blow_darts_bonus,
  			  :crossbows,		 :crossbows_bonus,
  			  :firearms,		 :firearms_bonus,
  			  :crystal_orbs,	 :crystal_orbs_bonus,
  			  :staffs,			 :staffs_bonus,
  			  :divine_tomes,	 :divine_tomes_bonus,
  			  :symbols,			 :symbols_bonus,
  			  :gemstones,		 :gemstones_bonus,
  			  :wands,			 :wands_bonus,
  			  :balance,			 :balance_bonus,
  			  :blocks,			 :blocks_bonus,
  			  :kicks,			 :kicks_bonus,
  			  :pain,			 :pain_bonus,
  			  :pressure_points,	 :pressure_points_bonus,
  			  :punches,			 :punches_bonus,
  			  :armors,			 :armors_bonus,
  			  :blades,			 :blades_bonus,
  			  :clothing,		 :clothing_bonus,
  			  :flails_c,		 :flails_c_bonus,
  			  :foods,			 :foods_bonus,
  			  :gauntlets,		 :gauntlets_bonus,
  			  :mallets_c,		 :mallets_c_bonus,
  			  :spears_c,		 :spears_c_bonus,
  			  :shields,			 :shields_bonus,
  			  :bows_c,			 :bows_c_bonus,
  			  :structures,		 :structures_bonus,
  			  :tools,			 :tools_bonus,
  			  :traps,			 :traps_bonus,
  			  :chemicals,		 :chemicals_bonus,
  			  :explosives,		 :explosives_bonus,
  			  :firearms_c,		 :firearms_c_bonus,
  			  :machines,		 :machines_bonus,
  			  :sorcery,			 :sorcery_bonus,
  			  :enchantment,		 :enchantment_bonus,
  			  :divine,			 :divine_bonus,
  			  :barding,			 :barding_bonus,
  			  :wizardry,		 :wizardry_bonus,
  			  :alchemy,			 :alchemy_bonus,
  				presence: true, numericality: { only_integer: true }

end
